# Generated by Django 5.1.1 on 2024-10-10 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depenserecurrente',
            name='statut',
        ),
        migrations.CreateModel(
            name='DepenseRecurrenteMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('statut', models.BooleanField(default=False)),
                ('depense_recurrente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.depenserecurrente')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('depense_recurrente', 'mois', 'annee')},
            },
        ),
    ]
